-- CREATE TABLE CUSTOMER (
--     CUSTNO INT PRIMARY KEY,
--     CNAME VARCHAR2(100),
--     CITY VARCHAR2(50)
-- );

-- CREATE TABLE ORDER_TABLE (
--     ORDERNO INT PRIMARY KEY,
--     CUSTNO INT,
--     ODATE DATE,
--     ORD_AMT REAL,
--     FOREIGN KEY (CUSTNO) REFERENCES CUSTOMER(CUSTNO)
-- );

-- CREATE TABLE ITEM (
--     ITEMNO INT PRIMARY KEY,
--     UNITPRICE REAL
-- );

-- CREATE TABLE ORDER_ITEM (
--     ORDERNO INT,
--     ITEMNO INT,
--     QTY INT,
--     PRIMARY KEY (ORDERNO, ITEMNO),
--     FOREIGN KEY (ORDERNO) REFERENCES ORDER_TABLE(ORDERNO),
--     FOREIGN KEY (ITEMNO) REFERENCES ITEM(ITEMNO)
-- );

-- CREATE TABLE WAREHOUSE (
--     WAREHOUSENO INT PRIMARY KEY,
--     CITY VARCHAR2(50)
-- );

-- CREATE TABLE SHIPMENT (
--     ORDERNO INT,
--     WAREHOUSENO INT,
--     SHIP_DATE DATE,
--     PRIMARY KEY (ORDERNO, WAREHOUSENO),
--     FOREIGN KEY (ORDERNO) REFERENCES ORDER_TABLE(ORDERNO),
--     FOREIGN KEY (WAREHOUSENO) REFERENCES WAREHOUSE(WAREHOUSENO)
-- );

INSERT INTO CUSTOMER (CUSTOMER_ID, CUSTOMER_NAME, CITY) 
VALUES (:customer_id, :customer_name, :city);

INSERT INTO ORDER_TABLE (ORDER_ID, CUSTOMER_ID, ORDER_DATE, TOTAL_AMOUNT)
VALUES (:order_id, :customer_id, TO_DATE(:order_date, 'YYYY-MM-DD'), :total_amount);

INSERT INTO ITEM (ITEM_ID, PRICE)
VALUES (:item_id, :price);

INSERT INTO ORDER_ITEM (ORDER_ID, ITEM_ID, QUANTITY)
VALUES (:order_id, :item_id, :quantity);

INSERT INTO WAREHOUSE (WAREHOUSE_ID, CITY)
VALUES (:warehouse_id, :city);

INSERT INTO SHIPMENT (ORDER_ID, WAREHOUSE_ID, SHIPMENT_DATE)
VALUES (:order_id, :warehouse_id, TO_DATE(:shipment_date, 'YYYY-MM-DD'));

SELECT
    S.ORDERNO,
    S.SHIP_DATE
FROM
    SHIPMENT  S
    JOIN WAREHOUSE W
    ON S.WAREHOUSENO = W.WAREHOUSENO
WHERE
    W.CITY = 'New York';

SELECT
    C.CUSTNO,
    C.CNAME,
    C.CITY,
    COUNT(O.ORDERNO) AS NO_OF_ORDERS,
    AVG(O.ORD_AMT)   AS AVG_ORDER_AMOUNT
FROM
    CUSTOMER    C
    JOIN ORDER_TABLE O
    ON C.CUSTNO = O.CUSTNO
GROUP BY
    C.CUSTNO,
    C.CNAME,
    C.CITY;

SELECT
    O.ORDERNO,
    O.ODATE,
    S.SHIP_DATE
FROM
    ORDER_TABLE O
    JOIN SHIPMENT S
    ON O.ORDERNO = S.ORDERNO
WHERE
    S.SHIP_DATE > O.ODATE + 30;



-- -- Insert data into CUSTOMER table
-- INSERT INTO CUSTOMER VALUES (1, 'Alice Johnson', 'New York');
-- INSERT INTO CUSTOMER VALUES (2, 'Bob Smith', 'Chicago');
-- INSERT INTO CUSTOMER VALUES (3, 'Charlie Brown', 'San Francisco');
-- INSERT INTO CUSTOMER VALUES (4, 'Diana Ross', 'Boston');
-- INSERT INTO CUSTOMER VALUES (5, 'Edward Norton', 'Austin');

-- -- Insert data into ORDER_TABLE
-- INSERT INTO ORDER_TABLE VALUES (101, 1, TO_DATE('2024-01-01', 'YYYY-MM-DD'), 500);
-- INSERT INTO ORDER_TABLE VALUES (102, 2, TO_DATE('2024-01-10', 'YYYY-MM-DD'), 1500);
-- INSERT INTO ORDER_TABLE VALUES (103, 3, TO_DATE('2024-02-01', 'YYYY-MM-DD'), 2000);
-- INSERT INTO ORDER_TABLE VALUES (104, 4, TO_DATE('2024-03-15', 'YYYY-MM-DD'), 250);
-- INSERT INTO ORDER_TABLE VALUES (105, 5, TO_DATE('2024-04-01', 'YYYY-MM-DD'), 3000);

-- -- Insert data into ITEM table
-- INSERT INTO ITEM VALUES (1, 100);
-- INSERT INTO ITEM VALUES (2, 200);
-- INSERT INTO ITEM VALUES (3, 150);
-- INSERT INTO ITEM VALUES (4, 250);
-- INSERT INTO ITEM VALUES (5, 300);

-- -- Insert data into ORDER_ITEM table
-- INSERT INTO ORDER_ITEM VALUES (101, 1, 5);
-- INSERT INTO ORDER_ITEM VALUES (102, 2, 3);
-- INSERT INTO ORDER_ITEM VALUES (103, 3, 4);
-- INSERT INTO ORDER_ITEM VALUES (104, 4, 2);
-- INSERT INTO ORDER_ITEM VALUES (105, 5, 1);

-- -- Insert data into WAREHOUSE table
-- INSERT INTO WAREHOUSE VALUES (1, 'New York');
-- INSERT INTO WAREHOUSE VALUES (2, 'Chicago');
-- INSERT INTO WAREHOUSE VALUES (3, 'San Francisco');
-- INSERT INTO WAREHOUSE VALUES (4, 'Boston');
-- INSERT INTO WAREHOUSE VALUES (5, 'Austin');

-- -- Insert data into SHIPMENT table
-- INSERT INTO SHIPMENT VALUES (101, 1, TO_DATE('2024-01-05', 'YYYY-MM-DD'));
-- INSERT INTO SHIPMENT VALUES (102, 2, TO_DATE('2024-01-20', 'YYYY-MM-DD'));
-- INSERT INTO SHIPMENT VALUES (103, 3, TO_DATE('2024-02-10', 'YYYY-MM-DD'));
-- INSERT INTO SHIPMENT VALUES (104, 4, TO_DATE('2024-04-19', 'YYYY-MM-DD'));  -- 35 days after 2024-03-15
-- INSERT INTO SHIPMENT VALUES (105, 5, TO_DATE('2024-05-06', 'YYYY-MM-DD'));


-- DROP TABLE SHIPMENT CASCADE CONSTRAINTS;
-- DROP TABLE ORDER_ITEM CASCADE CONSTRAINTS;
-- DROP TABLE ORDER_TABLE CASCADE CONSTRAINTS;
-- DROP TABLE ITEM CASCADE CONSTRAINTS;
-- DROP TABLE CUSTOMER CASCADE CONSTRAINTS;
-- DROP TABLE WAREHOUSE CASCADE CONSTRAINTS;
