CREATE TABLE STUDENT (
    REGNO VARCHAR2(10) PRIMARY KEY, 
    NAME VARCHAR2(20), 
    MAJOR VARCHAR2(20), 
    DOB DATE
);

CREATE TABLE COURSE (
    COURSENO NUMBER(10) PRIMARY KEY, 
    CNAME VARCHAR2(20), 
    DEPT VARCHAR2(30)
);

CREATE TABLE ENROLL (
    REGNO VARCHAR2(10) REFERENCES STUDENT, 
    COURSENO NUMBER(10) REFERENCES COURSE, 
    SEM NUMBER(5), 
    MARKS NUMBER(5)
);

CREATE TABLE TEXT (
    BKISBN NUMBER(13) PRIMARY KEY, 
    BOOK_TITLE VARCHAR2(20), 
    PUBLISHER VARCHAR2(50), 
    AUTHOR VARCHAR2(50)
);

CREATE TABLE BOOK_ADPT (
    COURSE_NO NUMBER(10) REFERENCES COURSE, 
    BKISBN NUMBER(13) REFERENCES TEXT, 
    SEM NUMBER(5)
);

INSERT INTO STUDENT (REGNO, NAME, MAJOR, DOB) 
VALUES (:regno, :name, :major, TO_DATE(:dob, 'DD-MON-YYYY'));

INSERT INTO COURSE (COURSENO, CNAME, DEPT) 
VALUES (:courseno, :cname, :dept);

INSERT INTO ENROLL (REGNO, COURSENO, SEM, MARKS) 
VALUES (:regno, :courseno, :sem, :marks);

INSERT INTO TEXT (BKISBN, BOOK_TITLE, PUBLISHER, AUTHOR) 
VALUES (:bkisbn, :book_title, :publisher, :author);

INSERT INTO BOOK_ADPT (COURSE_NO, BKISBN, SEM) 
VALUES (:course_no, :bkisbn, :sem);

CREATE VIEW COMPDEPT AS 
    SELECT C.DEPT, C.COURSENO, T.BOOK_TITLE, T.BKISBN 
    FROM COURSE C
    JOIN BOOK_ADPT BA ON C.COURSENO = BA.COURSE_NO
    JOIN TEXT T ON BA.BKISBN = T.BKISBN
    WHERE DEPT = 'CS'
    ORDER BY T.BOOK_TITLE;

SELECT * FROM COMPDEPT;

SELECT COURSENO, BKISBN, BOOK_TITLE 
FROM COMPDEPT 
WHERE DEPT IN (
    SELECT DEPT 
    FROM COMPDEPT 
    GROUP BY DEPT 
    HAVING COUNT(*) >= 2
);

SELECT C.DEPT, T.BOOK_TITLE, T.PUBLISHER 
FROM COURSE C
JOIN BOOK_ADPT B ON C.COURSENO = B.COURSE_NO
JOIN TEXT T ON B.BKISBN = T.BKISBN
WHERE T.PUBLISHER = 'McGraw Hill';


-- DROP TABLE BOOK_ADPT CASCADE CONSTRAINTS;
-- DROP TABLE TEXT CASCADE CONSTRAINTS;
-- DROP TABLE ENROLL CASCADE CONSTRAINTS;
-- DROP TABLE COURSE CASCADE CONSTRAINTS;
-- DROP TABLE STUDENT CASCADE CONSTRAINTS;
-- DROP VIEW COMPDEPT;


-- INSERT INTO STUDENT (REGNO, NAME, MAJOR, DOB) 
-- VALUES ('S001', 'Rahul', 'CS', TO_DATE('15-SEP-2002', 'DD-MON-YYYY'));

-- INSERT INTO STUDENT (REGNO, NAME, MAJOR, DOB) 
-- VALUES ('S002', 'Anjali', 'EC', TO_DATE('20-OCT-2001', 'DD-MON-YYYY'));

-- INSERT INTO STUDENT (REGNO, NAME, MAJOR, DOB) 
-- VALUES ('S003', 'Vikram', 'ME', TO_DATE('10-JUL-2000', 'DD-MON-YYYY'));

-- INSERT INTO STUDENT (REGNO, NAME, MAJOR, DOB) 
-- VALUES ('S004', 'Priya', 'EE', TO_DATE('25-DEC-2003', 'DD-MON-YYYY'));

-- INSERT INTO STUDENT (REGNO, NAME, MAJOR, DOB) 
-- VALUES ('S005', 'Naveen', 'CS', TO_DATE('18-JAN-2002', 'DD-MON-YYYY'));

-- INSERT INTO COURSE (COURSENO, CNAME, DEPT) 
-- VALUES (101, 'Data Structures', 'CS');

-- INSERT INTO COURSE (COURSENO, CNAME, DEPT) 
-- VALUES (102, 'Digital Electronics', 'EC');

-- INSERT INTO COURSE (COURSENO, CNAME, DEPT) 
-- VALUES (103, 'Thermodynamics', 'ME');

-- INSERT INTO COURSE (COURSENO, CNAME, DEPT) 
-- VALUES (104, 'Power Systems', 'EE');

-- INSERT INTO COURSE (COURSENO, CNAME, DEPT) 
-- VALUES (105, 'Operating Systems', 'CS');

-- INSERT INTO ENROLL (REGNO, COURSENO, SEM, MARKS) 
-- VALUES ('S001', 101, 3, 85);

-- INSERT INTO ENROLL (REGNO, COURSENO, SEM, MARKS) 
-- VALUES ('S002', 102, 4, 78);

-- INSERT INTO ENROLL (REGNO, COURSENO, SEM, MARKS) 
-- VALUES ('S003', 103, 2, 90);

-- INSERT INTO ENROLL (REGNO, COURSENO, SEM, MARKS) 
-- VALUES ('S004', 104, 1, 82);

-- INSERT INTO ENROLL (REGNO, COURSENO, SEM, MARKS) 
-- VALUES ('S005', 105, 3, 88);

-- INSERT INTO TEXT (BKISBN, BOOK_TITLE, PUBLISHER, AUTHOR) 
-- VALUES (9780131103627, 'Algorithms', 'Pearson', 'Cormen');

-- INSERT INTO TEXT (BKISBN, BOOK_TITLE, PUBLISHER, AUTHOR) 
-- VALUES (9780262033848, 'Computer Networks', 'McGraw Hill', 'Tanenbaum');

-- INSERT INTO TEXT (BKISBN, BOOK_TITLE, PUBLISHER, AUTHOR) 
-- VALUES (9780132350884, 'Clean Code', 'Prentice Hall', 'Robert Martin');

-- INSERT INTO TEXT (BKISBN, BOOK_TITLE, PUBLISHER, AUTHOR) 
-- VALUES (9780073523323, 'Digital Design', 'McGraw Hill', 'Morris Mano');

-- INSERT INTO TEXT (BKISBN, BOOK_TITLE, PUBLISHER, AUTHOR) 
-- VALUES (9780262035613, 'Operating Systems', 'Pearson', 'Silberschatz');

-- INSERT INTO BOOK_ADPT (COURSE_NO, BKISBN, SEM) 
-- VALUES (101, 9780131103627, 3);

-- INSERT INTO BOOK_ADPT (COURSE_NO, BKISBN, SEM) 
-- VALUES (102, 9780262033848, 4);

-- INSERT INTO BOOK_ADPT (COURSE_NO, BKISBN, SEM) 
-- VALUES (103, 9780132350884, 2);

-- INSERT INTO BOOK_ADPT (COURSE_NO, BKISBN, SEM) 
-- VALUES (104, 9780073523323, 1);

-- INSERT INTO BOOK_ADPT (COURSE_NO, BKISBN, SEM) 
-- VALUES (105, 9780262035613, 3);